name: 'My Job will help to Planning for display Message'
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: ubuntu-latest
    steps:
      
      
      - run: |
          ls
          echo "welcome"
          echo "Love bansal"
